---
title: "public transit service quality"
date: "`r Sys.Date()`"
author: "Flavio Poletti"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Public Transit Quality (ÖV-Güteklassen)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidytransit)
library(dplyr)
```

# Datensatz

https://opentransportdata.swiss/de/dataset/timetable-2021-gtfs2020

Download Datensatz
Auszug erstellen
Weiterarbeit mit Auszug (wäre auch mit Gesamtdatensatz möglich)

```{r Setup}
gtfs_zug_path = system.file("extdata", "gtfs_ch_zug.zip",  package = "tidytransit")
g = read_gtfs(gtfs_zug_path)
```
# Vorgehen

### Ausschnitt
```{r Subset, echo=F}
library(osmdata)
library(sf)
osmsf = opq(c(8.4820, 47.1494, 8.6003, 47.2328)) %>% 
  add_osm_feature(key = "admin_level", value = "8") %>% 
  osmdata_sf()

baar = osmsf$osm_multipolygons %>% filter(name == "Baar") %>% st_transform(2056)

stops = g$stops %>% 
  group_by(stop_name) %>%
  summarise(stop_lon = mean(stop_lon), stop_lat = mean(stop_lat))

stops = stops %>%
  sf::st_as_sf(coords = c("stop_lon", "stop_lat"), crs = 4326) %>% 
  sf::st_set_agr("constant") %>% 
  st_transform(2056) %>% 
  sf::st_intersection(sf::st_geometry(baar))
```

### Art der Verkehrsmittel
```{r Verkehrsmittel}
stop_times = g$stop_times[c("stop_id", "trip_id", "arrival_time", "departure_time")] %>% 
  inner_join(g$stops[c("stop_id", "stop_name")]) %>% 
  inner_join(g$trips[c("trip_id", "route_id")]) %>% 
  inner_join(g$routes[c("route_id", "route_type")])

verkehrsmittelgruppe = stop_times %>% 
  select(route_type) %>% unique() %>%
  inner_join(tidytransit::route_type_names) %>% 
  arrange(route_type)

verkehrsmittelgruppe
verkehrsmittelgruppe$Verkehrsmittelgruppe <- c(rep("A", 4), rep("B", 4), "C")

stop_times <- stop_times %>%
  inner_join(verkehrsmittelgruppe[c("route_type", "Verkehrsmittelgruppe")], "route_type")
```

### Bahnknoten/Bahnlinie
```{r Bahntypen}
bknoten_blinie = stop_times %>% 
  group_by(stop_name, Verkehrsmittelgruppe) %>% 
  summarise(n_routes = n_distinct(route_id), .groups = "drop")

bknoten_blinie$Verkehrsmittel <- bknoten_blinie$Verkehrsmittelgruppe
bknoten_blinie$Verkehrsmittel[which(bknoten_blinie$Verkehrsmittelgruppe == "A" & 
                                            bknoten_blinie$n_routes > 2)] <- "A1"
bknoten_blinie$Verkehrsmittel[which(bknoten_blinie$Verkehrsmittelgruppe == "A" & 
                                      bknoten_blinie$n_routes <= 2)] <- "A2"
bknoten_blinie$n_routes <- NULL

st_vm = stop_times %>% 
  inner_join(bknoten_blinie, c("stop_name", "Verkehrsmittelgruppe"))

```

### Kursintervall
```{r Kursintervall}
ARE_kursintervalle = c("< 5 Min.", ">=5 bis < 10 Min.", ">= 10 bis < 20 Min.",
                    ">= 20 bis < 40 Min.", ">= 40 bis <= 60 Min.")

st_vm_ki = st_vm %>% 
  filter(arrival_time >= hms::parse_hm("06:00")) %>%
  filter(arrival_time <= hms::parse_hm("20:00")) %>% 
  group_by(stop_name, Verkehrsmittel) %>% 
  count(name = "n_departures") %>% ungroup()

st_vm_ki <- st_vm_ki %>% 
  mutate(interval = (20-6)*60 / (n_departures/2)) %>% 
  mutate(Kursintervall = cut(interval, c(0, 5, 10, 20, 40, 60), 
                             right = F, labels = ARE_kursintervalle, 
                             ordered_result = T)) %>% 
  select(-interval, -n_departures)
```

### Haltestellenkategorie
```{r Haltestellenkategorie}
# TODO factor functions
ARE_haltestellenkategorie = tibble(
  Kursintervall = ARE_kursintervalle,
  A1 = c("I", "I", "II", "III", "IV"),
  A2 = c("I", "II", "III", "IV", "V"),
  B = c("II", "III", "IV", "V", "V"),
  C = c("V", "V", "V", "V", "V"))
ARE_haltestellenkategorie <- ARE_haltestellenkategorie %>%
  tidyr::gather("Verkehrsmittel", "Haltestellenkategorie", -Kursintervall) %>% 
  mutate(Kursintervall = factor(Kursintervall, ARE_kursintervalle, ordered = T))

hskat = inner_join(st_vm_ki, ARE_haltestellenkategorie, c("Verkehrsmittel", "Kursintervall")) %>% 
  mutate(Verkehrsmittel = factor(Verkehrsmittel, c("A1", "A2", "B", "C"), ordered = TRUE)) %>% 
  mutate(Haltestellenkategorie = factor(Haltestellenkategorie,  c("I", "II", "III", "IV", "V"), ordered = TRUE))
```

### Distanz zur Haltestelle
```{r Distanz}
ARE_gueteklasse = tibble(
  Haltestellenkategorie = c("I", "II", "III", "IV", "V"),
  "< 300 m" = c("A", "A", "B", "C", "D"),
  "300 - 500 m" = c("A", "B", "C", "D", "keine"),
  "501 - 750 m" = c("B", "C", "D", "keine", "keine"),
  "751 - 1000 m" = c("C", "D", "keine", "keine", "keine"))
ARE_gueteklasse <- ARE_gueteklasse %>%
  tidyr::gather("Distanz", "Gueteklasse", -Haltestellenkategorie) %>% 
  filter(Gueteklasse != "keine") %>% 
  mutate(Haltestellenkategorie = factor(Haltestellenkategorie, c("I", "II", "III", "IV", "V"), ordered = TRUE)) %>% 
  mutate(Gueteklasse = factor(Gueteklasse, c("A", "B", "C", "D"), ordered = TRUE)) %>% 
  mutate(Distanz = factor(Distanz, c("< 300 m", "300 - 500 m", "501 - 750 m", "751 - 1000 m"), ordered = TRUE))

distance_num = tibble(Distanz = levels(ARE_gueteklasse$Distanz),
                      distance = c(300, 500, 750, 1000))
```

### ÖV-Güteklasse
```{r Gueteklasse}
stop_dist = stops %>% 
  inner_join(hskat, "stop_name") %>%
  inner_join(ARE_gueteklasse, "Haltestellenkategorie") %>% 
  inner_join(distance_num, "Distanz") %>% 
  filter(Gueteklasse != "keine")
  
gueteklassen = st_buffer(stop_dist, stop_dist$distance)

gueteklassen %>% arrange(desc(Gueteklasse)) %>% select(Gueteklasse) %>% plot()

gueteklassen <- gueteklassen %>% 
  select(Gueteklasse) %>% 
  group_by(Gueteklasse) %>% 
  summarise() %>% 
  arrange(Gueteklasse) %>% 
  st_difference()
```

## Map

```{r Map}
mapview::mapview(gueteklassen, layer.name = "Güteklasse")
```