utils::globalVariables(
  c(
    "field_provided_status",
    "field_spec",
    "file_provided_status",
    "file_spec",
    "route_id",
    "service_id",
    "shape_id",
    "stop_id",
    "stop_lat",
    "stop_lon",
    "stop_name",
    "trip_id",
    "validation_details",
    "start_date",
    "end_date",
    "exception_type",
    "arrival_time",
    "departure_time"
  )
)
